#ifndef SDA_PLATFORM_H
#define SDA_PLATFORM_H
#include "main.h"

// Constants
#define MIN_VOLTAGE 3.1
#define MAX_VOLTAGE 4.0
#define BATT_ADC_CONST_DEF 0.001275255
#define VOLTAGE_REF_VAL_DEF 0.626


// Pin state defs
#define SDA_BASE_PIN_IN 0
#define SDA_BASE_PIN_OUT 1
#define SDA_BASE_PIN_ALT 2

#define SDA_BASE_PIN_NOPULL 0
#define SDA_BASE_PIN_PULLDOWN 1
#define SDA_BASE_PIN_PULLUP 1


// Pinout
#define SDA_BASE_SYSLED_PORT GPIOB
#define SDA_BASE_SYSLED_PIN GPIO_PIN_2

#define SDA_BASE_SPEAKER_PORT GPIOB
#define SDA_BASE_SPEAKER_PIN GPIO_PIN_1

#define SDA_BASE_BTN_A_PIN GPIO_PIN_15
#define SDA_BASE_BTN_A_PORT GPIOB

#define SDA_BASE_BTN_LEFT_PIN GPIO_PIN_10
#define SDA_BASE_BTN_LEFT_PORT GPIOA

#define SDA_BASE_BTN_UP_PIN GPIO_PIN_14
#define SDA_BASE_BTN_UP_PORT GPIOB

#define SDA_BASE_BTN_DOWN_PIN GPIO_PIN_13
#define SDA_BASE_BTN_DOWN_PORT GPIOB

#define SDA_BASE_BTN_RIGHT_PIN GPIO_PIN_9
#define SDA_BASE_BTN_RIGHT_PORT GPIOA

#define SDA_BASE_BTN_B_PIN GPIO_PIN_12
#define SDA_BASE_BTN_B_PORT GPIOB

#define SDA_BASE_USB_DETECT_PIN GPIO_PIN_7
#define SDA_BASE_USB_DETECT_PORT GPIOB

void Delay(__IO uint32_t nCount);

void sda_platform_board_rev_detect();
void sda_serial_enable();

#endif
